import { wrap } from 'svelte-spa-router/wrap';

import Home from './pages/home/ScriptableHome.svelte';
import Demo from './pages/home/Home.svelte';

export const routes = {
    '/': Home,
    '/button': wrap({ asyncComponent: () => import('./pages/button/ButtonDemo.svelte') }),
    '/icon': wrap({ asyncComponent: () => import('./pages/icon/IconDemo.svelte') }),
    '/navBar': wrap({ asyncComponent: () => import('./pages/navBar/NavBarDemo.svelte') }),
    '/divider': wrap({ asyncComponent: () => import('./pages/divider/DividerDemo.svelte') }),
    '/cell': wrap({ asyncComponent: () => import('./pages/cell/CellDemo.svelte') }),
    '/switch': wrap({ asyncComponent: () => import('./pages/switch/SwitchDemo.svelte') }),
    '/avatar': wrap({ asyncComponent: () => import('./pages/avatar/AvatarDemo.svelte') }),
    '/tabs': wrap({ asyncComponent: () => import('./pages/tabs/TabsDemo.svelte') }),
    '/tabBar': wrap({ asyncComponent: () => import('./pages/tabBar/TabBarDemo.svelte') }),
    '/steps': wrap({ asyncComponent: () => import('./pages/steps/StepsDemo.svelte') }),
    '/indexBar': wrap({ asyncComponent: () => import('./pages/indexBar/IndexBarDemo.svelte') }),
    '/radio': wrap({ asyncComponent: () => import('./pages/radio/RadioDemo.svelte') }),
    '/checkbox': wrap({ asyncComponent: () => import('./pages/checkbox/CheckboxDemo.svelte') }),
    '/input': wrap({ asyncComponent: () => import('./pages/input/InputDemo.svelte') }),
    '/grids': wrap({ asyncComponent: () => import('./pages/grids/GridsDemo.svelte') }),
    '/swiper': wrap({ asyncComponent: () => import('./pages/swiper/SwiperDemo.svelte') }),
    '/placeholder': wrap({ asyncComponent: () => import('./pages/placeholder/PlaceholderDemo.svelte') }),
    '/skeleton': wrap({ asyncComponent: () => import('./pages/skeleton/SkeletonDemo.svelte') }),
    '/rate': wrap({ asyncComponent: () => import('./pages/rate/RateDemo.svelte') }),
    '/slider': wrap({ asyncComponent: () => import('./pages/slider/SliderDemo.svelte') }),
    '/badge': wrap({ asyncComponent: () => import('./pages/badge/BadgeDemo.svelte') }),
    '/noticeBar': wrap({ asyncComponent: () => import('./pages/noticeBar/NoticeBarDemo.svelte') }),
    '/progress': wrap({ asyncComponent: () => import('./pages/progress/ProgressDemo.svelte') }),
    '/progressLoop': wrap({ asyncComponent: () => import('./pages/progressLoop/ProgressLoopDemo.svelte') }),
    '/mask': wrap({ asyncComponent: () => import('./pages/mask/MaskDemo.svelte') }),
    '/toast': wrap({ asyncComponent: () => import('./pages/toast/ToastDemo.svelte') }),
    '/loading': wrap({ asyncComponent: () => import('./pages/loading/LoadingDemo.svelte') }),
    '/popup': wrap({ asyncComponent: () => import('./pages/popup/PopupDemo.svelte') }),
    '/bottomSheet': wrap({ asyncComponent: () => import('./pages/bottomSheet/BottomSheetDemo.svelte') }),
    '/modal': wrap({ asyncComponent: () => import('./pages/modal/ModalDemo.svelte') }),
    '/dialog': wrap({ asyncComponent: () => import('./pages/dialog/DialogDemo.svelte') }),
    '/actionSheet': wrap({ asyncComponent: () => import('./pages/actionSheet/ActionSheetDemo.svelte') }),
    '/picker': wrap({ asyncComponent: () => import('./pages/picker/PickerDemo.svelte') }),
    '/asyncPicker': wrap({ asyncComponent: () => import('./pages/asyncPicker/AsyncPickerDemo.svelte') }),
    '/timePicker': wrap({ asyncComponent: () => import('./pages/timePicker/TimePickerDemo.svelte') }),
    '/calendar': wrap({ asyncComponent: () => import('./pages/calendar/CalendarDemo.svelte') }),
    '/demo': Demo,
    '*': Home,
};
